# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      r:
        - oldrel
        - release
        - devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r:
        - oldrel
        - release
        - devel
    - os: osx
      osx_image: xcode8.1
      r:
        - oldrel
        - release
        - devel
    - os: osx
      osx_image: beta-xcode6.4
      r:
        - oldrel
        - release
        - devel
    - os: osx
      r:
        - oldrel
        - release
        - devel
