# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
git:
  depth: 150

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
    #- os: linux
    #  dist: trusty
    #  r: devel
    # Memory faults?


    - os: osx
      osx_image: xcode8.1
      r: release

    - os: osx
      r: release

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
